# Day 5 - Data Cleaning using Pandas

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("employee.csv")
df

    Employee_ID              Name   Age    Salary  Department
0           101  Sachin Tendulkar  50.0  120000.0  Management
1           102       Virat Kohli  36.0   95000.0   Marketing
2           103          MS Dhoni  44.0       NaN  Operations
3           104      Rohit Sharma  38.0   90000.0       Sales
4           105    Jasprit Bumrah  31.0   85000.0          IT
5           106      Rahul Dravid   NaN  100000.0    Training
6           107         Kapil Dev  66.0  110000.0  Management
7           108   Sir Don Bradman  40.0  130000.0    Research
8           109     Ricky Ponting  50.0       NaN          HR
9           110       Shane Warne  52.0   95000.0     Finance
10          111        Brian Lara  55.0   98000.0  Operations
11          112  Sir Viv Richards  73.0  125000.0  Management
12          113        Ben Stokes  34.0   87000.0         NaN
13          114   Kane Williamson  35.0   91000.0          IT
14          115        Babar Azam  31.0   88000.0   Marketing
15          101  Sachin Tendulkar  50.0  120000.0  Management
16          109     Ricky Ponting  50.0       NaN          HR

In [4]:
print(df.isnull().sum())

Employee_ID    0
Name           0
Age            1
Salary         3
Department     1
dtype: int64

In [5]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
df["Department"] = df["Department"].fillna("Unknown")
df

    Employee_ID              Name      Age         Salary  Department
0           101  Sachin Tendulkar  50.0000  120000.000000  Management
1           102       Virat Kohli  36.0000   95000.000000   Marketing
2           103          MS Dhoni  44.0000  102428.571429  Operations
3           104      Rohit Sharma  38.0000   90000.000000       Sales
4           105    Jasprit Bumrah  31.0000   85000.000000          IT
5           106      Rahul Dravid  45.9375  100000.000000    Training
6           107         Kapil Dev  66.0000  110000.000000  Management
7           108   Sir Don Bradman  40.0000  130000.000000    Research
8           109     Ricky Ponting  50.0000  102428.571429          HR
9           110       Shane Warne  52.0000   95000.000000     Finance
10          111        Brian Lara  55.0000   98000.000000  Operations
11          112  Sir Viv Richards  73.0000  125000.000000  Management
12          113        Ben Stokes  34.0000   87000.000000     Unknown
13          114   Kane Williamson  35.0000   91000.000000          IT
14          115        Babar Azam  31.0000   88000.000000   Marketing
15          101  Sachin Tendulkar  50.0000  120000.000000  Management
16          109     Ricky Ponting  50.0000  102428.571429          HR

In [6]:
df = df.drop_duplicates()
df

    Employee_ID              Name      Age         Salary  Department
0           101  Sachin Tendulkar  50.0000  120000.000000  Management
1           102       Virat Kohli  36.0000   95000.000000   Marketing
2           103          MS Dhoni  44.0000  102428.571429  Operations
3           104      Rohit Sharma  38.0000   90000.000000       Sales
4           105    Jasprit Bumrah  31.0000   85000.000000          IT
5           106      Rahul Dravid  45.9375  100000.000000    Training
6           107         Kapil Dev  66.0000  110000.000000  Management
7           108   Sir Don Bradman  40.0000  130000.000000    Research
8           109     Ricky Ponting  50.0000  102428.571429          HR
9           110       Shane Warne  52.0000   95000.000000     Finance
10          111        Brian Lara  55.0000   98000.000000  Operations
11          112  Sir Viv Richards  73.0000  125000.000000  Management
12          113        Ben Stokes  34.0000   87000.000000     Unknown
13          114   Kane Williamson  35.0000   91000.000000          IT
14          115        Babar Azam  31.0000   88000.000000   Marketing

In [7]:
print(df.dtypes)

Employee_ID      int64
Name               str
Age            float64
Salary         float64
Department         str
dtype: object

In [8]:
df["Age"] = df["Age"].astype(int)
print(df.dtypes)

Employee_ID      int64
Name               str
Age              int64
Salary         float64
Department         str
dtype: object

In [9]:
print(df)

    Employee_ID              Name  Age         Salary  Department
0           101  Sachin Tendulkar   50  120000.000000  Management
1           102       Virat Kohli   36   95000.000000   Marketing
2           103          MS Dhoni   44  102428.571429  Operations
3           104      Rohit Sharma   38   90000.000000       Sales
4           105    Jasprit Bumrah   31   85000.000000          IT
5           106      Rahul Dravid   45  100000.000000    Training
6           107         Kapil Dev   66  110000.000000  Management
7           108   Sir Don Bradman   40  130000.000000    Research
8           109     Ricky Ponting   50  102428.571429          HR
9           110       Shane Warne   52   95000.000000     Finance
10          111        Brian Lara   55   98000.000000  Operations
11          112  Sir Viv Richards   73  125000.000000  Management
12          113        Ben Stokes   34   87000.000000     Unknown
13          114   Kane Williamson   35   91000.000000          IT
14          115        Babar Azam   31   88000.000000   Marketing

In [10]:
df.to_csv("cleaned_employees.csv", index=False)
print("Clean dataset saved successfully!")

Clean dataset saved successfully!